# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: amirpourmand/al-folio:slim
    #build: .
    ports:
      - 3000:8080
      - 35729:35729
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
